AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance with cloud-init
Parameters: 
  keyName:
    Description: Key name
    Type: AWS::EC2::KeyPair::KeyName
  ImageId:
    Description: Centos 7 image id
    Type: AWS::EC2::Image::Id

Resources: 
  AdminSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:  Enable SSH
      VpcId: !ImportValue VPC:Id
      SecurityGroupIngress:
      -  IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AdminSecGroup

  DataInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Tags:
        - Key: Name
          Value: DataInterface
      PrivateIpAddress: 10.1.2.100
      SubnetId: !ImportValue 'SubnetPvtA:Id'
  
  DataInterfaceAttachment:
    Type: AWS::EC2::NetworkInterfaceAttachment
    Properties:
      InstanceId: !Ref EC2Instance
      DeviceIndex: "1"
      NetworkInterfaceId: !Ref DataInterface

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keyName
      ImageId: !Ref ImageId
      InstanceType: t2.nano
      SubnetId: !ImportValue 'SubnetPubA:Id'
      PrivateIpAddress: 10.1.1.100
      Monitoring: false
      # SecurityGroups:
      SecurityGroupIds:
        - Ref: AdminSecGrp
      UserData: 
        Fn::Base64: !Sub |
          #cloud-config
          manage_resolv_conf: true
          resolv_conf:
            nameservers: ['8.8.4.4', '8.8.8.8']

          network: {config: disabled}
          # Hostname management
          preserve_hostname: False
          hostname: centos7-test14
          fqdn: centos7-test14

          users:
            - name: "shankar"
              groups:
                - sudo
                - wheel
              sudo: ['ALL=(ALL) NOPASSWD:ALL']
              ssh-authorized-keys:
                - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCVR8MG7WnFVXoa ... "
                - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDrg7d4KuQQvDz/ ... "

          packages:
            - yum-utils
            - wget
            - git
            - vim-enhanced

          bootcmd:
            - set -x; echo '#user-data/bootcmd:' >> /etc/sysconfig/network-scripts/ifcfg-ens2
            - set -x; sed -i -e '/^BOOTPROTO/ s/dhcp/static/g' -e '/PERSISTENT_DHCLIENT/d' /etc/sysconfig/network-scripts/ifcfg-ens2
            - set -x; echo 'IPADDR=10.1.1.100' >> /etc/sysconfig/network-scripts/ifcfg-ens2
            - set -x; echo 'NETMASK=255.255.255.0' >> /etc/sysconfig/network-scripts/ifcfg-ens2
            - set -x; echo 'GATEWAY=10.1.1.1' >> /etc/sysconfig/network-scripts/ifcfg-ens2
            - set -x; echo 'DNS1=8.8.8.8' >> /etc/sysconfig/network-scripts/ifcfg-ens2
            - set -x; echo 'ONBOOT="yes"' >> /etc/sysconfig/network-scripts/ifcfg-ens2
            - set -x; echo 'NM_CONTROLLED=no' >> /etc/sysconfig/network-scripts/ifcfg-ens2
            - set -x; echo 'DEFROUTE=yes' >> /etc/sysconfig/network-scripts/ifcfg-ens2
            - ifdown ens2
            - ifup ens2


          write_files:
          - path: /root/runfile.sh
            content: |
              #!/bin/bash -e
              setenforce 0
              > /etc/sysconfig/network-scripts/ifcfg-eth0
              read MACeth1 </sys/class/net/eth1/address
              echo '#user-data/bootcmd:' >> /etc/sysconfig/network-scripts/ifcfg-eth1
              sed -i -e '/^BOOTPROTO/ s/dhcp/static/g' -e '/PERSISTENT_DHCLIENT/d' /etc/sysconfig/network-scripts/ifcfg-eth1
              echo HWADDR=$MACeth1 >> /etc/sysconfig/network-scripts/ifcfg-eth1

              echo 'IPADDR=10.1.2.100' >> /etc/sysconfig/network-scripts/ifcfg-eth1
              echo 'NETMASK=255.255.255.0' >> /etc/sysconfig/network-scripts/ifcfg-eth1
              echo 'GATEWAY=10.1.2.1' >> /etc/sysconfig/network-scripts/ifcfg-eth1
              echo 'DNS1=8.8.8.8' >> /etc/sysconfig/network-scripts/ifcfg-eth1
              echo 'ONBOOT="yes"' >> /etc/sysconfig/network-scripts/ifcfg-eth1
              echo 'NM_CONTROLLED=no' >> /etc/sysconfig/network-scripts/ifcfg-eth1
              echo 'DEFROUTE=no' >> /etc/sysconfig/network-scripts/ifcfg-eth1
              ifdown eth1
              ifup eth1
            permissions: '0700'

          runcmd:
          - systemctl disable NetworkManager
          - chmod a+x /root/runfile.sh
          - /root/runfile.sh
      Tags:
        - Key: Name
          Value: CloudInit
