baseurl = "/"
languageCode = "en-us"
title = "Casper Theme"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Technical Blogging Site"
  cover = "images/cover.jpg"
  author = "Shankar Nagarajan"
  authorlocation = "Sydney, Australia"
  authorwebsite = ""
  bio= "my bio"
  logo = "images/logo.png"
  # googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = ""
  githubName = "omshankar1"
  twitterName = "shank_iisc"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
